services:
    percona:
        image: percona
        restart: always
        ports:
            - '3317:3306'
        environment:
            MYSQL_ROOT_PASSWORD: pass#();

    yugabyte:
        image: yugabytedb/yugabyte
        command: bin/yugabyted start --daemon=false
        ports:
            - "5434:5432"
        environment:
            YSQL_USER: root
            YSQL_PASSWORD: pass#();

    cockroach:
        image: cockroachdb/cockroach
        command: start-single-node --insecure
        ports:
            - "26257:26257"
        environment:
            COCKROACH_USER: 'root'
            COCKROACH_PASSWORD: 'pass#();'
