version: '2.1'

services:
    pd0:
        image: pingcap/pd:latest
        ports:
            - "2379"
        volumes:
            - ./config/pd.toml:/pd.toml:ro
        command:
            - --name=pd0
            - --client-urls=http://0.0.0.0:2379
            - --peer-urls=http://0.0.0.0:2380
            - --advertise-client-urls=http://pd0:2379
            - --advertise-peer-urls=http://pd0:2380
            - --initial-cluster=pd0=http://pd0:2380
            - --data-dir=/data/pd0
            - --config=/pd.toml
            - --log-file=/logs/pd0.log
        restart: on-failure
    tikv0:
        image: pingcap/tikv:latest
        volumes:
            - ./config/tikv.toml:/tikv.toml:ro
        command:
            - --addr=0.0.0.0:20160
            - --advertise-addr=tikv0:20160
            - --data-dir=/data/tikv0
            - --pd=pd0:2379
            - --config=/tikv.toml
            - --log-file=/logs/tikv0.log
        depends_on:
            - "pd0"
        restart: on-failure

    tidb:
        image: pingcap/tidb:latest
        ports:
            - "4000:4000"
            - "10080:10080"
        volumes:
            - ./config/tidb.toml:/tidb.toml:ro
        command:
            - --store=tikv
            - --path=pd0:2379
            - --config=/tidb.toml
            - --log-file=/logs/tidb.log
            - --advertise-address=tidb
        depends_on:
            - "tikv0"
        restart: on-failure
    tispark-master:
        image: pingcap/tispark:v2.1.1
        command:
            - /opt/spark/sbin/start-master.sh
        volumes:
            - ./config/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf:ro
        environment:
            SPARK_MASTER_PORT: 7077
            SPARK_MASTER_WEBUI_PORT: 8080
        ports:
            - "7077:7077"
            - "8080:8080"
        depends_on:
            - "tikv0"
        restart: on-failure
    tispark-slave0:
        image: pingcap/tispark:v2.1.1
        command:
            - /opt/spark/sbin/start-slave.sh
            - spark://tispark-master:7077
        volumes:
            - ./config/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf:ro
        environment:
            SPARK_WORKER_WEBUI_PORT: 38081
        ports:
            - "38081:38081"
        depends_on:
            - tispark-master
        restart: on-failure

    tidb-vision:
        image: pingcap/tidb-vision:latest
        environment:
            PD_ENDPOINT: pd0:2379
        ports:
            - "8010:8010"
        restart: on-failure

    # monitors
    pushgateway:
        image: prom/pushgateway:v0.3.1
        command:
            - --log.level=error
        restart: on-failure
    prometheus:
        user: root
        image: prom/prometheus:v2.2.1
        command:
            - --log.level=error
            - --storage.tsdb.path=/data/prometheus
            - --config.file=/etc/prometheus/prometheus.yml
        ports:
            - "9090:9090"
        volumes:
            - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
            - ./config/pd.rules.yml:/etc/prometheus/pd.rules.yml:ro
            - ./config/tikv.rules.yml:/etc/prometheus/tikv.rules.yml:ro
            - ./config/tidb.rules.yml:/etc/prometheus/tidb.rules.yml:ro

        restart: on-failure
    grafana:
        image: grafana/grafana:6.0.1
        user: "0"
        environment:
            GF_LOG_LEVEL: error
            GF_PATHS_PROVISIONING: /etc/grafana/provisioning
            GF_PATHS_CONFIG: /etc/grafana/grafana.ini
        volumes:
            - ./config/grafana:/etc/grafana
            - ./config/dashboards:/tmp/dashboards
        ports:
            - "3000:3000"
        restart: on-failure
